apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-allports-service1
spec:
  podSelector:
    matchLabels:
      app: service1
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
